apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      #image: jenkins/inbound-agent:jdk11-windowsservercore-1809
      image: jenkins/inbound-agent:jdk17-windowsservercore-ltsc2019
      #image: jenkins/inbound-agent:jdk17-windowsservercore-ltsc2019
      #command: ["sleep", "10000"]
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
          ephemeral-storage: "4Gi"
        limits:
          memory: "10Gi"
          cpu: "4"
          ephemeral-storage: "4Gi"
  nodeSelector:
    kubernetes.io/os: windows