apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-deployment
spec:
  selector:
    matchLabels:
      app: win
  replicas: 2
  template:
    metadata:
      labels:
        app: win
    spec:
      containers:
        - name: win
          image: mcr.microsoft.com/powershell:preview-windowsservercore-1809
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "24Gi"
              cpu: "16"
              ephemeral-storage: "16Gi"
            limits:
              memory: "25Gi"
              cpu: "17"
              ephemeral-storage: "24Gi"
          command:
            - powershell
          args:
            - Start-Sleep
            - "999999"
      nodeSelector:
        kubernetes.io/os: windows