apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-windows
spec:
  nodeSelector:
    key: workload
    value: build
  tolerations:
  - key: node.kubernetes.io/os
    operator: Equal
    value: windows
    effect: NoSchedule
  - key: nodeType
    operator: Equal
    value: winbuild
    effect: NoSchedule
  containers:
    - name: jnlp
      image: artifactory.test.dentsplysirona.com/devops-docker-remote-hub/jenkins/inbound-agent:windowsservercore-ltsc2019
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "8Gi"
          cpu: "4"
    - name: build-env-win
      image: artifactory.test.dentsplysirona.com/mpdp-docker-local-dev/windows/build-env-win:17.2.3
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "24Gi"
          cpu: "16"
          ephemeral-storage: "16Gi"
        limits:
          memory: "25Gi"
          cpu: "17"
          ephemeral-storage: "24Gi"
      command:
        - powershell
      args:
      - Start-Sleep
      - 999999
      restartPolicy: OnFailure
  imagePullSecrets:
  - name: regcred
