---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      #image: jenkins/inbound-agent:jdk11-windowsservercore-1809
      image: jenkins/inbound-agent:3077.vd69cf116da_6f-4-jdk11-windowsservercore-ltsc2019
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
          ephemeral-storage: "4Gi"
        limits:
          memory: "10Gi"
          cpu: "4"
          ephemeral-storage: "4Gi"
    - name: windows
      image: mcr.microsoft.com/powershell:preview-windowsservercore-1809
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
          ephemeral-storage: "1Gi"
        limits:
          memory: "8Gi"
          cpu: "4"
          ephemeral-storage: "2Gi"
      imagePullPolicy: IfNotPresent
      command:
        - powershell
      args:
        - Start-Sleep
        - 999999
  nodeSelector:
    kubernetes.io/os: windows