apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:jdk11-windowsservercore-1809
    - name: windows
      image: mcr.microsoft.com/powershell:preview-windowsservercore-1809
      imagePullPolicy: IfNotPresent
      command:
        - powershell
      args:
        - Start-Sleep
        - 999999
  nodeSelector:
    kubernetes.io/os: windows